import { FiSearch } from "react-icons/fi";

const metadata = {
  title: "Search",
  description: "Generated by create next app",
};

const Search = () => {
  return (
    <div className="mx-auto p-4 max-w-[800px]">
      <form className="flex items-center gap-2">
        <input className="w-full bg-gray-200 dark:bg-[#333] placeholder:text-[#888] text-[#ccc] h-[30px] outline-none px-4 py-5 rounded-full" type="text" placeholder="What would you like to cook?" />
        <button className="rounded-full bg-orange-600 h-[36px] w-[36px] flex items-center justify-center text-white text-xl p-[6px]" type="submit"><FiSearch /></button>
      </form>
    </div>
  )
}

export default Search