import { Favitem } from "@/components/Favitem";
import { Navbar } from "@/components/Navbar";

const metadata = {
  title: "Fav List",
  description: "Generated by create next app",
};

const Fav = () => {
  return (
    <div>
      <Navbar />
      <div className="px-4">
        <h3 className="dark:text-[#ccc] text-center font-semibold mb-4">My Favorites</h3>
        <Favitem />
        <Favitem />
        <Favitem />
        <Favitem />
        <Favitem />
        <Favitem />
        <Favitem />
      </div>
    </div>
  )
}

export default Fav