import { LoggedNavbar } from "@/components/LoggedNavbar";
import { Item } from "@/components/Item";
import { MdFavoriteBorder } from "react-icons/md";

const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function Page() {
  return <div className="">
    <LoggedNavbar />
    <div className="bg-white dark:bg-black max-w-[1400px] mx-auto sticky top-[50px]">
      <div className="flex gap-2 px-4 py-2 mb-2 overflow-x-auto no-scrollbar">
        <p className="text-sm bg-gray-200 dark:bg-[#222] dark:text-[#ccc] w-fit py-1 px-4 rounded-full cursor-pointer">All</p>
        <p className="text-sm bg-gray-200 dark:bg-[#222] dark:text-[#ccc] w-fit py-1 px-4 rounded-full cursor-pointer">Cake</p>
        <p className="text-sm bg-gray-200 dark:bg-[#222] dark:text-[#ccc] w-fit py-1 px-4 rounded-full cursor-pointer">Pizza</p>
        <p className="text-sm bg-gray-200 dark:bg-[#222] dark:text-[#ccc] w-fit py-1 px-4 rounded-full cursor-pointer">Chocolate</p>
        <p className="text-sm bg-gray-200 dark:bg-[#222] dark:text-[#ccc] w-fit py-1 px-4 rounded-full cursor-pointer">Juice</p>
      </div>
    </div>

    <div className="bg-white dark:bg-black px-4 mx-auto max-w-[1400px] gap-4 grid grid-cols-1 tablet:grid-cols-2 laptop:grid-cols-3 desktop:grid-cols-4">
    <Item />
    <Item />
    <Item />
    <Item />
    <Item />
    <Item />
    <Item />
    <Item />
    </div>


  </div>
}