'use client'

import styles from "./page.module.css";
import { Navbar } from "../components/Navbar";
import { Item } from "../components/Item";
import { MdFavoriteBorder } from "react-icons/md";
import { useEffect, useState } from "react";
import { Tag } from "../components/Tag";

const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function Page() {

  // const getItems = async () => {
  //   try {
  //     const res = await fetch('http://127.0.0.1:3000/api/items', {
  //       cache: 'no-store',
  //     })

  //     if (!res.ok) {
  //       throw new Error('Failed to fetch items.')
  //     }

  //     return res.json()

  //   } catch (error) {
  //     console.log('Error loading items.', error)
  //   }
  // }
  // const items = getItems()
  // console.log(items)

  const [name, setName] = useState('');
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(false)
  const [search, setSearch] = useState('')
  const [category, setCategory] = useState('chicken')

  const onSearch = async (e) => {
    const res = await fetch(`https://www.themealdb.com/api/json/v1/1/search.php?s=${search}`)
    console.log(res)
    if (!res.ok) {
      return;
    }
    const data = await res.json()
    setData(data)

  }

  const onSearch1 = async (e) => {
    const res = await fetch(`https://www.themealdb.com/api/json/v1/1/search.php?s=chicken`)
    console.log(res)
    if (!res.ok) {
      return;
    }
    const data = await res.json()
    setData(data)

  }

  const onSearch2 = async (e) => {
    const res = await fetch(`https://www.themealdb.com/api/json/v1/1/search.php?s=vegan`)
    console.log(res)
    if (!res.ok) {
      return;
    }
    const data = await res.json()
    setData(data)

  }

  const onSearch3 = async (e) => {
    const res = await fetch(`https://www.themealdb.com/api/json/v1/1/search.php?s=lamb`)
    console.log(res)
    if (!res.ok) {
      return;
    }
    const data = await res.json()
    setData(data)

  }

  const onSearch4 = async (e) => {
    const res = await fetch(`https://www.themealdb.com/api/json/v1/1/search.php?s=pork`)
    console.log(res)
    if (!res.ok) {
      return;
    }
    const data = await res.json()
    setData(data)

  }

  const onSearch5 = async (e) => {
    const res = await fetch(`https://www.themealdb.com/api/json/v1/1/search.php?s=pasta`)
    console.log(res)
    if (!res.ok) {
      return;
    }
    const data = await res.json()
    setData(data)

  }

  const onSearch6 = async (e) => {
    const res = await fetch(`https://www.themealdb.com/api/json/v1/1/search.php?s=seafood`)
    console.log(res)
    if (!res.ok) {
      return;
    }
    const data = await res.json()
    setData(data)

  }

  useEffect(() => {
    setLoading(true)
    const fetchData = async () => {
      try {
        const res = await fetch(`https://www.themealdb.com/api/json/v1/1/filter.php?i=${name}`);
        console.log(res)
        if (!res.ok) {
          throw new Error('Failed to fetch data');
        }
        const result = await res.json();
        setData(result);
      } catch (error) {
        console.error('Error fetching data:', error);
      }
      setLoading(false)
    };

    fetchData();
  }, [name]);

  return (<>
    <Navbar />
    <div className="bg-white dark:bg-black max-w-[1400px] mx-auto sticky top-[50px]">
      <div className="flex gap-2 px-4 py-2 mb-2 overflow-x-auto no-scrollbar">
        <div onClick={onSearch}><Tag tagCat={'All'} /></div>
        <div onClick={onSearch1}><Tag tagCat={'Chicken'} /></div>
        <div onClick={onSearch2}><Tag tagCat={'Vegan'} /></div>
        <div onClick={onSearch3}><Tag tagCat={'Lamb'} /></div>
        <div onClick={onSearch4}><Tag tagCat={'Pork'} /></div>
        <div onClick={onSearch5}><Tag tagCat={'Pasta'} /></div>
        <div onClick={onSearch6}><Tag tagCat={'Seafood'} /></div>
      </div>
    </div>

    <div className="bg-white dark:bg-black px-4 mx-auto max-w-[1400px] gap-4 grid grid-cols-1 tablet:grid-cols-2 laptop:grid-cols-3 desktop:grid-cols-4">

      <>
        {data?.meals?.map((meal) => (
          <Item key={meal.idMeal} meal={meal} />
        ))}
      </>
    </div>


  </>
  )
}