'use client';

import { PiCookingPotBold } from "react-icons/pi";
import Link from "next/link";
import React, { useEffect } from "react";
import {useRouter} from "next/navigation";
import axios from "axios";
import { toast } from "react-hot-toast";

const metadata = {
  title: "Sign Up",
  description: "Generated by create next app",
};

export default function page() {

  const router = useRouter();
    const [user, setUser] = React.useState({
        email: "",
        password: "",
        username: "",
    })

    const [buttonDisabled, setButtonDisabled] = React.useState(false);
    const [loading, setLoading] = React.useState(false);

    const onSignup = async () => {
      try {
          setLoading(true);
          const response = await axios.post("/api/users/signup", user);
          console.log("Signup success", response.data);
          router.push("/account/signin");
          
      } catch (error) {
          console.log("Signup failed", error.message);
          
          toast.error(error.message);
      }finally {
          setLoading(false);
      }
  }

  useEffect(() => {
    if(user.email.length > 0 && user.password.length > 0 && user.username.length > 0) {
        setButtonDisabled(false);
    } else {
        setButtonDisabled(true);
    }
}, [user]);

  return (
    <div className="">
        <div className="flex justify-center mt-[100px] mb-[30px]">
        <Link href={'/'}><PiCookingPotBold className="bg-orange-600 p-2 text-5xl rounded-full text-white" /></Link>
        </div>
        <div className="flex mt-4 flex-col gap-2 max-w-[300px] mx-auto">
          <p className="text-sm dark:text-[#888]">Username</p>
          <input 
          value={user.username}
          onChange={(e) => setUser({...user, username: e.target.value})}
          className="bg-gray-200 dark:bg-[#222] dark:text-[#ccc] p-2 rounded-lg"
          type="text"
          />
          <p className="text-sm dark:text-[#888]">Email Address</p>
          <input
          value={user.email}
          onChange={(e) => setUser({...user, email: e.target.value})}
          className="bg-gray-200 dark:bg-[#222] dark:text-[#ccc] p-2 rounded-lg" 
          type="text" />

          <p className="text-sm dark:text-[#888]">Password</p>
          <input 
          value={user.password}
          onChange={(e) => setUser({...user, password: e.target.value})}
          className="bg-gray-200 dark:bg-[#222] dark:text-[#ccc] p-2 rounded-lg" 
          type="password" />

          <button 
          className="bg-black dark:bg-[#333] text-white py-2 px-8 rounded-lg mt-2"
          onClick={onSignup}
          >Sign up</button>
          <Link className="mt-4 text-sm text-center dark:text-[#888]" href={'/account/signin'}>Already have an account? Sign in.</Link>
        </div>
    </div>
  )
}
