'use client'

import styles from "./../../page.module.css";
import { MdFavoriteBorder } from "react-icons/md";
import { useEffect, useState } from "react";
import { LoggedNavbar } from "../../../components/LoggedNavbar";
import { Tag } from "../../../components/Tag";
import { LoggedItem } from "../../../components/LoggedItem";
import axios from "axios";
import Link from "next/link";
import {toast} from "react-hot-toast";
import {useRouter} from "next/navigation";

const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function Page() {

  const [name, setName] = useState('');
  const [data, setData] = useState(null);
  const[loading,setLoading] = useState(false)
  const [search, setSearch] = useState('')
  const [category, setCategory] = useState('chicken')
  const router = useRouter()
    const [loggedData, setLoggedData] = useState("nothing")
    
    const getUserDetails = async () => {
      const res = await axios.get('/api/users/user')
      console.log(res.user);
      setLoggedData(res.user.data._id)
    }

    useEffect(() => {
      const res = axios.get('/api/users/user')
      console.log(res.user);
      //setLoggedData(res.user.data._id)

      loggedData !== 'nothing' ? router.push(`/account/signin`) : router.push(`/account/user`)
    }, [])
    

  const onSearch = async (e) => {
    const res = await fetch(`https://www.themealdb.com/api/json/v1/1/search.php?s=${search}`)
    console.log(res)
    if (!res.ok) {
      return;
    }
    const data = await res.json()
    setData(data)
    
  }

  const onSearch1 = async (e) => {
    const res = await fetch(`https://www.themealdb.com/api/json/v1/1/search.php?s=chicken`)
    console.log(res)
    if (!res.ok) {
      return;
    }
    const data = await res.json()
    setData(data)
    
  }

  const onSearch2 = async (e) => {
    const res = await fetch(`https://www.themealdb.com/api/json/v1/1/search.php?s=vegan`)
    console.log(res)
    if (!res.ok) {
      return;
    }
    const data = await res.json()
    setData(data)
    
  }

  const onSearch3 = async (e) => {
    const res = await fetch(`https://www.themealdb.com/api/json/v1/1/search.php?s=lamb`)
    console.log(res)
    if (!res.ok) {
      return;
    }
    const data = await res.json()
    setData(data)
    
  }

  const onSearch4 = async (e) => {
    const res = await fetch(`https://www.themealdb.com/api/json/v1/1/search.php?s=pork`)
    console.log(res)
    if (!res.ok) {
      return;
    }
    const data = await res.json()
    setData(data)
    
  }
  
  const onSearch5 = async (e) => {
    const res = await fetch(`https://www.themealdb.com/api/json/v1/1/search.php?s=pasta`)
    console.log(res)
    if (!res.ok) {
      return;
    }
    const data = await res.json()
    setData(data)
    
  }
  
  const onSearch6 = async (e) => {
    const res = await fetch(`https://www.themealdb.com/api/json/v1/1/search.php?s=seafood`)
    console.log(res)
    if (!res.ok) {
      return;
    }
    const data = await res.json()
    setData(data)
    
  }

  useEffect(() => {
    setLoading(true)
    const fetchData = async () => {
      try {
        const res = await fetch(`https://www.themealdb.com/api/json/v1/1/filter.php?i=${name}`);
        console.log(res)
        if (!res.ok) {
          throw new Error('Failed to fetch data');
        }
        const result = await res.json();
        setData(result);
      } catch (error) {
        console.error('Error fetching data:', error);
      }
      setLoading(false)
    };

    fetchData();
  }, [name]);

  return (<>
    <LoggedNavbar />
    <div className={'dark:text-[#ccc]'}>{loggedData === 'nothing' ? "Nothing" : <Link href={`/account/user`}>{loggedData}
            </Link>}</div>
    <div className="bg-white dark:bg-black max-w-[1400px] mx-auto sticky top-[50px]">
      <div className="flex gap-2 px-4 py-2 mb-2 overflow-x-auto no-scrollbar">
        <div onClick={onSearch}><Tag tagCat={'All'} /></div>
        <div onClick={onSearch1}><Tag tagCat={'Chicken'} /></div>
        <div onClick={onSearch2}><Tag tagCat={'Vegan'} /></div>
        <div onClick={onSearch3}><Tag tagCat={'Lamb'} /></div>
        <div onClick={onSearch4}><Tag tagCat={'Pork'} /></div>
        <div onClick={onSearch5}><Tag tagCat={'Pasta'} /></div>
        <div onClick={onSearch6}><Tag tagCat={'Seafood'} /></div>
      </div>
    </div>

    <div className="bg-white dark:bg-black px-4 mx-auto max-w-[1400px] gap-4 grid grid-cols-1 tablet:grid-cols-2 laptop:grid-cols-3 desktop:grid-cols-4">

    <>
            {data?.meals?.map((meal) => (
              <LoggedItem key={meal.idMeal} meal={meal} />
            ))}
            </>
    </div>


  </>
)}